//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.07 at 12:08:55 AM CST 
//


package oasis.names.tc.xacml._2_0.context.schema.os;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import an.xacml.Constants;


/**
 * <p>Java class for StatusCodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatusCodeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:2.0:context:schema:os}StatusCode" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatusCodeType", namespace = "urn:oasis:names:tc:xacml:2.0:context:schema:os", propOrder = {
    "statusCode"
})
public class StatusCodeType {
    public static final StatusCodeType EVAL_STATUS_OK = new StatusCodeType(Constants.STATUS_OK, null);
    public static final StatusCodeType EVAL_STATUS_MISSINGATTRIBUTE = new StatusCodeType(Constants.STATUS_MISSINGATTRIBUTE, null);
    public static final StatusCodeType EVAL_STATUS_SYNTAXERROR = new StatusCodeType(Constants.STATUS_SYNTAXERROR, null);
    public static final StatusCodeType EVAL_STATUS_PROCESSINGERROR = new StatusCodeType(Constants.STATUS_PROCESSINGERROR, null);
    public static final StatusCodeType EVAL_STATUS_SERVERERROR = new StatusCodeType(Constants.STATUS_SERVERERROR, null);
    public static final StatusCodeType EVAL_STATUS_UNKNOWNERROR = new StatusCodeType(Constants.STATUS_UNKNOWNERROR, null);

    @XmlElement(name = "StatusCode", namespace = "urn:oasis:names:tc:xacml:2.0:context:schema:os")
    protected StatusCodeType statusCode;
    @XmlAttribute(name = "Value", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String value;

    /**
     * Default constructor
     */
    public StatusCodeType() {}

    /**
     * For fast construct the default status code values
     * @param value
     * @param child
     */
    public StatusCodeType(String value, StatusCodeType child) {
        this.value = value;
        this.statusCode = child;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link StatusCodeType }
     *     
     */
    public StatusCodeType getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusCodeType }
     *     
     */
    public void setStatusCode(StatusCodeType value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
