//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.07 at 12:08:55 AM CST 
//


package oasis.names.tc.xacml._2_0.policy.schema.os;

import static an.xacml.Constants.TYPE_BOOLEAN;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;

import org.w3c.dom.Element;


/**
 * <p>Java class for AttributeValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttributeValueType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:oasis:names:tc:xacml:2.0:policy:schema:os}ExpressionType">
 *       &lt;sequence>
 *         &lt;any processContents='lax' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DataType" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributeValueType", namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", propOrder = {
    "content"
})
@XmlSeeAlso({
    AttributeAssignmentType.class
})
public class AttributeValueType {

    public static final AttributeValueType TRUE = new AttributeValueType(TYPE_BOOLEAN, Boolean.TRUE);
    public static final AttributeValueType FALSE = new AttributeValueType(TYPE_BOOLEAN, Boolean.TRUE);

    @XmlMixed
    @XmlAnyElement(lax = true)
    protected List<Object> content;
    @XmlAttribute(name = "DataType", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String dataType;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * The typed value represents the corresponding Java typed attribute value. It should be the final evaluated
     * value, regardless it has child expression or not. This typed value field will not be serialized to XML document,
     * it's designed for keep the evaluation result w/o modify the original content of the XML element.
     * 
     * Users should use getContent() method to get original document or add contents to it to write policy back to
     * document.
     * 
     * Defined it as transient to prevent JAXB map it to XML document.
     */
    @XmlTransient
    private Object typedValue;

    /**
     * The default constructor
     * FIXME can we set it as packaged? could it impact the JAXB XML-Object loading/mapping?
     */
    /* packaged */ AttributeValueType() {}

    /**
     * The convenient constructor for the TRUE/FALSE constants.
     * @param dataType
     * @param value
     */
    /* packaged */ AttributeValueType(String dataType, Object value) {
        this.dataType = dataType;
        this.typedValue = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * {@link String }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataType(String value) {
        this.dataType = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

    /**
     * We only provided a getter because it's the evaluation result, not the original content.
     * @return
     */
    public Object getTypedValue() {
        return typedValue;
    }

    /**
     * Internally used. Set the evaluation result.
     * @param typedValue
     */
    /* packaged */ void setTypedValue(Object typedValue) {
        this.typedValue = typedValue;
    }
}
